#!/bin/sh
# Fans ~/Desktop/outagewatch.env out to the gitignored files each tool reads:
#   TEAM_ID                      -> mobile/iosApp/Configuration/Local.xcconfig
#   FIREBASE_* / KEYSTORE_* /
#   KEY_ALIAS / API_BASE_URL     -> mobile/local.properties
# The env file stays outside the repo, this script never prints a secret, and
# it refuses to write anything git would not ignore. Blank values in the env
# leave whatever a file already has, so re-running is always safe.
#
# Usage: sh mobile/scripts/sync-secrets.sh [path-to-env]

set -eu

ENV_FILE="${1:-$HOME/Desktop/outagewatch.env}"
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
XCCONFIG="$REPO_ROOT/mobile/iosApp/Configuration/Local.xcconfig"
PROPS="$REPO_ROOT/mobile/local.properties"

[ -f "$ENV_FILE" ] || { echo "error: $ENV_FILE not found"; exit 1; }

# Read one key's value from the env file: last assignment wins, first '=' splits,
# surrounding whitespace and optional quotes stripped. Never echoed by callers.
val() {
    grep "^[[:space:]]*$1=" "$ENV_FILE" | tail -1 | cut -d= -f2- \
        | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
              -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'\$/\1/"
}

# Both generated files must be invisible to git before a byte is written.
for f in "$XCCONFIG" "$PROPS"; do
    git -C "$REPO_ROOT" check-ignore -q "$f" 2>/dev/null \
        || { echo "error: $f is not gitignored; refusing to write secrets"; exit 1; }
done

# ---- iOS: Local.xcconfig ----------------------------------------------------
TEAM_ID="$(val TEAM_ID)"
if [ -n "$TEAM_ID" ]; then
    printf '// Generated by mobile/scripts/sync-secrets.sh. Do not commit.\nTEAM_ID=%s\n' "$TEAM_ID" > "$XCCONFIG"
    chmod 600 "$XCCONFIG"
    echo "wrote Local.xcconfig (TEAM_ID set)"
else
    echo "TEAM_ID empty, leaving Local.xcconfig alone"
fi

# ---- Android: local.properties ----------------------------------------------
KEYS="FIREBASE_APP_ID FIREBASE_API_KEY FIREBASE_PROJECT_ID FIREBASE_SENDER_ID KEYSTORE_FILE KEYSTORE_PASSWORD KEY_ALIAS API_BASE_URL"
touch "$PROPS"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
cp "$PROPS" "$TMP"
updated=0
for key in $KEYS; do
    v="$(val "$key")"
    [ -n "$v" ] || continue
    grep -v "^$key=" "$TMP" > "$TMP.next" || true
    printf '%s=%s\n' "$key" "$v" >> "$TMP.next"
    mv "$TMP.next" "$TMP"
    updated=$((updated + 1))
    echo "set $key"
done
if [ "$updated" -gt 0 ]; then
    cp "$TMP" "$PROPS" && chmod 600 "$PROPS"
    echo "updated local.properties ($updated key(s))"
else
    echo "no Android keys set in the env, local.properties untouched"
fi

# ---- Reminders for the pieces this script cannot do --------------------------
[ -f "$REPO_ROOT/mobile/iosApp/iosApp/GoogleService-Info.plist" ] \
    || echo "note: GoogleService-Info.plist missing; fetch it per docs/APP_STORE.md"
APNS_PATH="$(val APNS_KEY_PATH)"
if [ -n "$APNS_PATH" ]; then
    # Compare lowercased: the default macOS filesystem is case-insensitive, so
    # Code/ and code/ are the same tree.
    lower_path="$(printf '%s' "$APNS_PATH" | tr '[:upper:]' '[:lower:]')"
    lower_root="$(printf '%s' "$REPO_ROOT" | tr '[:upper:]' '[:lower:]')"
    case "$lower_path" in
        "$lower_root"*) echo "WARNING: the .p8 is inside the repo tree; move it out" ;;
        *) [ -f "$APNS_PATH" ] || echo "note: APNS_KEY_PATH points at a missing file" ;;
    esac
fi
echo "done"
